const path=require('node:path');
const {pathToFileURL}=require('node:url');
const assert=require('node:assert/strict');
const {connectBrowser,collectDiagnostics,writeReport}=require('./browser-utils.cjs');

async function main(){
  const browser=await connectBrowser();
  const context=await browser.newContext({viewport:{width:1440,height:1000}});
  const page=await context.newPage();const diagnostics=collectDiagnostics(page),consoleLocations=[];
  page.on('console',message=>{if(message.type()==='error')consoleLocations.push(message.location());});
  const fileUrl=pathToFileURL(path.resolve(__dirname,'../index.html')).href+'?qa=1';
  await page.goto(fileUrl,{waitUntil:'networkidle'});
  await page.waitForFunction(()=>EmberDemo.getState().assetsReady);
  const fileState=await page.evaluate(()=>EmberDemo.getState());
  assert.equal(fileState.mode,'ready');
  await page.locator('#overlayButton').click();
  const firstJump=await page.evaluate(()=>{const a=EmberDemo;a.input.press('Space');a.step(1);a.input.release('Space');return a.getState();});
  assert.equal(firstJump.player.airJump,1,'immediate grounded jump must preserve air jump');
  assert.ok(firstJump.player.vy<0);
  await page.goto('http://127.0.0.1:8791/?qa=1',{waitUntil:'networkidle'});
  await page.waitForFunction(()=>EmberDemo.getState().assetsReady);
  await page.evaluate(()=>{const a=EmberDemo;a.loadLevel(1);a.debugTeleport(400,325);a.input.press('ShiftLeft');a.step(1);a.input.release('ShiftLeft');});
  let rect=await page.locator('canvas').boundingBox();
  await page.mouse.click(rect.x+485/960*rect.width,rect.y+325/540*rect.height,{button:'right'});
  const actualMouse=await page.evaluate(()=>{EmberDemo.step(40);return EmberDemo.getState();});
  assert.equal(actualMouse.player.state,'anchor');
  assert.equal(actualMouse.player.anchorId,'first');
  await page.evaluate(()=>{EmberDemo.loadLevel(6);EmberDemo.debugTeleport(600,180);});
  rect=await page.locator('canvas').boundingBox();
  await page.mouse.move(rect.x+770/960*rect.width,rect.y+115/540*rect.height);
  await page.mouse.down({button:'left'});
  await page.evaluate(()=>EmberDemo.step(12));
  await page.mouse.up({button:'left'});
  const shot=await page.evaluate(()=>{const fired=EmberDemo.getState();EmberDemo.step(60);return {fired,after:EmberDemo.getState()};});
  assert.ok(shot.after.torches.find(t=>t.id==='relay-distant').lit,'charged shot must light aimed torch');
  const anchoredDeath=await page.evaluate(()=>{const a=EmberDemo;a.loadLevel(7);a.input.mouse(280,365,'right',true);a.step(1);a.input.mouse(280,365,'right',false);a.step(40);const anchored=a.getState();let n=0;while(a.getState().mode==='playing'&&n++<500)a.step(1);return {anchored,frames:n,after:a.getState()};});
  assert.equal(anchoredDeath.anchored.player.anchorId,'chase-one');
  assert.equal(anchoredDeath.after.mode,'dead','chase must kill idle anchored player');
  await page.locator('#helpButton').click();
  const dialogPause=await page.evaluate(()=>{const before=EmberDemo.getState();EmberDemo.step(200);return {before,after:EmberDemo.getState(),open:document.querySelector('#helpDialog').open};});
  assert.ok(dialogPause.open);
  assert.equal(dialogPause.before.time,dialogPause.after.time,'dead timer must stop behind modal');
  assert.equal(dialogPause.after.mode,'dead');
  await page.locator('#closeHelpButton').click();
  const recovered=await page.evaluate(()=>{EmberDemo.step(80);return EmberDemo.getState();});
  assert.equal(recovered.mode,'playing');
  assert.equal(recovered.player.x,72);
  const output=writeReport('focused-checks-report.json',{fileUrl,fileState,firstJump,actualMouse,shot,anchoredDeath,dialogPause,recovered,diagnostics,consoleLocations});
  console.log(JSON.stringify({output,fileReady:fileState.assetsReady,mouseAnchor:actualMouse.player.anchorId,shotLit:shot.after.torches.find(t=>t.id==='relay-distant').lit,anchorDeath:anchoredDeath.after.mode,modalPaused:dialogPause.open,diagnostics,consoleLocations},null,2));
  assert.deepEqual(diagnostics,{pageErrors:[],consoleErrors:[],failedRequests:[],badResponses:[]});
  await browser.close();
}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});
